- name:  Windows Update
  hosts: windows
  gather_facts: false
  tasks:
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        reboot: yes
